// src/components/Basic/Basic.tsx
import * as React from 'react';
import { mapRootStateToProps, RootComponent } from 'core/RootComponent/RootComponent';
import { RootState } from 'redux/Store';
import { BasicProps } from 'core/RootComponent/BasicProps';
import { connect } from 'react-redux';
import Mousetrap from 'mousetrap';
import Log from 'utils/Log';
import { configPara, getConfig, setConfig } from 'utils/ConfigPara';
import { BasicState } from 'core/RootComponent/BasicState';
const { remote } = window.require('electron');

export interface IBasicProps extends BasicProps {
    searching: any;
    setting: any;
    isSettingOpened?: boolean;

}
export interface IBasicStates extends BasicState {
    config: typeof configPara
}
class Basic extends RootComponent<IBasicProps, IBasicStates> {
    constructor(props: Readonly<IBasicProps>) {
        super(props);
        this.state = {
            config: configPara
        }
    }

    async componentDidMount() {
        var config = await getConfig()
        Log.Info(config);
        this.setState({ config })

        const word = document.querySelector('#word') as HTMLInputElement;
        word.focus();
        word.value = '';
        Mousetrap.bind('esc', () => { this.miniMize(); });

        Mousetrap.bind(['command+f', 'ctrl+f'], e => {
            const word = document.querySelector('#word') as HTMLInputElement;
            word.focus();
            word.value = '';
        })
        Mousetrap.bind('j', function () {
            const word = document.querySelector('#wordShowing') as HTMLDivElement;
            if (word) word.scrollTop += 20;
        });
        Mousetrap.bind('k', function () {
            const word = document.querySelector('#wordShowing') as HTMLDivElement;
            if (word) word.scrollTop -= 20;
        });

        Mousetrap.bind('J', function () {
            window.scrollTo(window.scrollX, window.scrollY + 20);
        });
        Mousetrap.bind('K', function () {
            window.scrollTo(window.scrollX, window.scrollY - 20);
        });
    }
    miniMize() {
        remote.BrowserWindow.getFocusedWindow().minimize();
    }
    toggleSetting() {
        document.querySelector('.wrapper')?.classList.toggle('toggled');
    }
    async settingSave(type: string, value: string) {
        Log.Info(this.state.config.default);
        switch (type) {
            case 'source':
                this.state.config.default.source = value;
                break;
            case 'playSound':
                this.state.config.default.playSound = value;
                break;
            default:
                break;
        }
        this.setState({ config: this.state.config });
        await setConfig(this.state.config.default);
    }
    public render() {
        const { isSettingOpened } = this.props;
        return (
            <>
                <div className="modal fade" id="settingModal" role="dialog" aria-hidden="true" style={{ background: 'transparent' }}>
                    <div className="modal-dialog" role="document">
                        <div className="modal-content">
                            <div className="modal-body">
                                <h2>Setting</h2>
                                <hr />
                                <div className="form-group">
                                    <label>Language you know:</label>
                                    <select className="form-control" value={this.state.config.default.source} onChange={e => { this.settingSave('source', e.target.value) }}>
                                        {
                                            this.state.config.languageSource.map(item => (<option value={item.value}>{item.name}</option>))
                                        }
                                    </select>
                                </div>
                                <div className="form-group">
                                    <label>Auto play word Sound?</label>
                                    <select className="form-control" value={this.state.config.default.playSound} onChange={e => { this.settingSave('playSound', e.target.value) }}>
                                        {
                                            this.state.config.playSoundOptions.map(item => (<option value={item.value}>{item.name}</option>))
                                        }
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div className="modal-footer">
                            <button type="button" className="btn btn-secondary" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
                <div className={isSettingOpened ? 'wrapper toggled' : 'wrapper'}>
                    <div className="content">
                        {this.props.searching}
                    </div>
                    <div id="sidebar" className="sidebar">
                        {this.props.setting}
                    </div>
                </div>
            </>
        );
    }
}

const mapStateToProps = (state: RootState) => ({
    isSettingOpened: state.system.isSettingOpened,
    ...mapRootStateToProps(state),
})
export default connect(mapStateToProps)(Basic)

// src/app/basic/basic.component.ts
import { OnInit, Component } from '@angular/core';
import * as https from 'https';
// import * as fs from 'fs-extra';
import * as readline from 'readline';
import * as storage from 'electron-json-storage';
import * as pdfkit from 'pdfkit';
import { remote, shell } from 'electron';
import * as Mousetrap from 'mousetrap';
import Word from '../word.model';
import { File, Filter } from '../file.utility';
import { setConfig, initConfig, configPara } from '../config';
import { ipcRenderer } from 'electron';
@Component({
  selector: 'app-root',
  templateUrl: './basic.component.html',
  styleUrls: ['./basic.component.css']
})
export class BasicComponent implements OnInit {
  sourceList;
  sourceCurrent;
  targetList;
  targetCurrent;
  soundList;
  soundCurrent;
  constructor() { }

  async ngOnInit() {
    await initConfig();
    this.sourceList = configPara.languageSource;
    this.sourceCurrent = configPara.default.source;
    this.targetList = configPara.languageTarget;
    this.targetCurrent = configPara.default.target;
    this.soundList = configPara.playSoundOptions;
    this.soundCurrent = configPara.default.playSound;
    Mousetrap.bind('esc', () => { this.miniMize(); });
    ipcRenderer.on('message', function (event, text) {
      if (text === 'downloaded') {
        document.querySelector('#infoAlert').classList.remove('d-none');
      }
    });
  }

  update() {
    ipcRenderer.send('message', 'update');
  }

  miniMize() {
    remote.BrowserWindow.getFocusedWindow().minimize();
  }

  toggleSetting(){
    document.querySelector('.wrapper').classList.toggle('toggled');
  }
  async settingSave() {
    await setConfig('source', this.sourceCurrent);
    await setConfig('target', this.targetCurrent);
    await setConfig('playSound', this.soundCurrent);
  }
}

<!-- Alert -->
<div id="infoAlert" class="alert alert-warning alert-dismissible d-none" role="alert">
  <strong>Info!</strong>
  <span id="messages">You have new update downloaded, do you want to update?</span>
  <button type="button" class="btn-primary" (click)="update()">Update</button>
  <button type="button" class="btn-warning" data-dismiss="alert" aria-label="Close">
    Later
  </button>
</div>
<!-- Modal -->
<div class="modal fade" id="settingModal" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-body">
        <h2>Setting</h2>
        <hr>
        <div class="form-group">
          <label>Language you know:</label>
          <select [(ngModel)]="sourceCurrent" class="form-control">
            <option *ngFor="let element of sourceList" [value]="element.value">{{element.name}}</option>
          </select>
        </div>
        <div class="form-group">
          <label>Language you learn:</label>
          <select [(ngModel)]="targetCurrent" class="form-control">
            <option *ngFor="let element of targetList" [value]="element.value">{{element.name}}</option>
          </select>
        </div>
        <div class="form-group">
          <label>Auto play word Sound?</label>
          <select [(ngModel)]="soundCurrent" class="form-control">
            <option *ngFor="let element of soundList" [value]="element.value">{{element.name}}</option>
          </select>
        </div>
        <div class="d-flex justify-content-end">
          <button class="btn btn-success m-1" (click)="settingSave()" data-dismiss="modal">Save</button>
          <button class="btn btn-danger m-1" data-dismiss="modal">Cancle</button>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="wrapper sticky-top">
  <div class="content">
    <app-serach-word [basicComponent]="this" #searchWord></app-serach-word>
  </div>
  <div id="sidebar" class="sidebar">
    <app-setting #setting [searchWordComponent]="searchWord"></app-setting>
  </div>
</div>
